import React, { useState } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';

const Login = () => {
  const navigate = useNavigate(); // Declared the navigation hook
  
  // State variables to capture typed data and display messages
  const [formData, setFormData] = useState({ email: '', password: '' });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  // Handle typing inside input boxes dynamically
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Triggered when user clicks the Submit/Login button
  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage('');
    setError('');

    try {
      // Direct pipeline request to your running backend port 5000
      const response = await axios.post('http://localhost:5000/api/auth/login', formData);
      
      setMessage(response.data.message);
      
      // Save your secure JWT badge into the browser's memory storage!
      localStorage.setItem('token', response.data.token);
      localStorage.setItem('user', JSON.stringify(response.data.user));

      console.log('User Badge Saved! Details:', response.data.user);

      // Automatically forward the user to the dashboard after a 1-second delay
      setTimeout(() => {
        navigate('/dashboard');
      }, 1000);

    } catch (err) {
      // Capture the exact error response message generated by your backend
      setError(err.response?.data?.message || 'Server connection failed. Try again.');
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h2 style={styles.heading}>College Management System</h2>
        <p style={styles.subheading}>Sign in to your account</p>

        {message && <div style={styles.successAlert}>✅ {message}</div>}
        {error && <div style={styles.errorAlert}>❌ {error}</div>}

        <form onSubmit={handleSubmit} style={styles.form}>
          <div style={styles.inputGroup}>
            <label style={styles.label}>College Email</label>
            <input 
              type="email" 
              name="email" 
              value={formData.email}
              onChange={handleChange}
              placeholder="enter your email Address" 
              style={styles.input} 
              required 
            />
          </div>

          <div style={styles.inputGroup}>
            <label style={styles.label}>Password</label>
            <input 
              type="password" 
              name="password" 
              value={formData.password}
              onChange={handleChange}
              placeholder="••••••••" 
              style={styles.input} 
              required 
            />
          </div>

          <button type="submit" style={styles.button}>Login</button>
          
          {/* Visual redirect link to jump to registration without page refreshes */}
          <p style={styles.redirectText}>
            Don't have an account?{' '}
            <Link to="/register" style={styles.redirectLink}>
              Sign Up here
            </Link>
          </p>
        </form>
      </div>
    </div>
  );
};

// Inline CSS Styles to make it look clean and professional
const styles = {
  container: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', backgroundColor: '#f4f6f9', fontFamily: 'Arial, sans-serif' },
  card: { backgroundColor: '#fff', padding: '40px', borderRadius: '10px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)', width: '100%', maxWidth: '400px', textAlign: 'center' },
  heading: { margin: '0 0 10px 0', color: '#1a73e8', fontSize: '24px', fontWeight: 'bold' },
  subheading: { margin: '0 0 20px 0', color: '#5f6368', fontSize: '14px' },
  form: { display: 'flex', flexDirection: 'column', gap: '15px' },
  inputGroup: { display: 'flex', flexDirection: 'column', textAlign: 'left', gap: '5px' },
  label: { fontSize: '13px', fontWeight: 'bold', color: '#3c4043' },
  input: { padding: '10px 12px', borderRadius: '5px', border: '1px solid #dadce0', fontSize: '14px', outline: 'none' },
  button: { padding: '12px', backgroundColor: '#1a73e8', color: '#fff', border: 'none', borderRadius: '5px', fontSize: '16px', cursor: 'pointer', fontWeight: 'bold', marginTop: '10px', transition: 'background 0.2s' },
  successAlert: { backgroundColor: '#e6f4ea', color: '#137333', padding: '10px', borderRadius: '5px', fontSize: '14px', marginBottom: '15px', textAlign: 'left' },
  errorAlert: { backgroundColor: '#fce8e6', color: '#c5221f', padding: '10px', borderRadius: '5px', fontSize: '14px', marginBottom: '15px', textAlign: 'left' },
  redirectText: { marginTop: '20px', fontSize: '14px', color: '#5f6368' },
  redirectLink: { color: '#1a73e8', fontWeight: 'bold', textDecoration: 'none' }
};

export default Login;